In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load the housing data.  First you need to upload the 'ModBostonHousing.pkl' file
housing_data = pd.read_pickle("ModBostonHousing.pkl")

In [21]:
housing_data['HOMEPRICE2CAT']

0      b'H'
1      b'L'
2      b'L'
3      b'H'
4      b'H'
       ... 
501    b'H'
502    b'H'
503    b'L'
504    b'L'
505    b'H'
Name: HOMEPRICE2CAT, Length: 506, dtype: bytes8

In [4]:
X = housing_data.iloc[:, 0:11]
X

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
0    1.23247   0.0   8.14   0.0  0.538  6.142   91.7  3.9769   4.0  307.0   
1    0.02177  82.5   2.03   0.0  0.415  7.610   15.7  6.2700   2.0  348.0   
2    4.89822   0.0  18.10   0.0  0.631  4.970  100.0  1.3325  24.0  666.0   
3    0.03961   0.0   5.19   0.0  0.515  6.037   34.5  5.9853   5.0  224.0   
4    3.69311   0.0  18.10   0.0  0.713  6.376   88.4  2.5671  24.0  666.0   
..       ...   ...    ...   ...    ...    ...    ...     ...   ...    ...   
501  3.47428   0.0  18.10   1.0  0.718  8.780   82.9  1.9047  24.0  666.0   
502  0.07896   0.0  12.83   0.0  0.437  6.273    6.0  4.2515   5.0  398.0   
503  1.83377   0.0  19.58   1.0  0.605  7.802   98.2  2.0407   5.0  403.0   
504  0.35809   0.0   6.20   1.0  0.507  6.951   88.5  2.8617   8.0  307.0   
505  2.92400   0.0  19.58   0.0  0.605  6.101   93.0  2.2834   5.0  403.0   

     PTRATIO  
0      18.72  
1       3.11  
2       3.26  
3       8.01  
4      14.65  
..       ...  
501     5.29  
502     6.78  
503     1.92  
504     9.71  
505     9.81  

[506 rows x 11 columns]

In [10]:
y = np.zeros((len(housing_data["HOMEPRICE2CAT"])))
print(type(y))
y

<class 'numpy.ndarray'>


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [9]:
y.size

506

In [11]:
y[housing_data["HOMEPRICE2CAT"] == b'H'] = 1

In [12]:
y

array([1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0.

In [15]:
["HOMEPRICE2CAT"] == b'H'

False

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=82)

In [17]:
X_train

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
115  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622   3.0  222.0   
334  4.22239   0.0  18.10   1.0  0.770  5.803  89.0  1.9047  24.0  666.0   
274  0.09512   0.0  12.83   0.0  0.437  6.286  45.0  4.5026   5.0  398.0   
231  0.25915   0.0  21.89   0.0  0.624  5.693  96.0  1.7883   4.0  437.0   
489  0.14455  12.5   7.87   0.0  0.524  6.172  96.1  5.9505   5.0  311.0   
..       ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
461  0.57834  20.0   3.97   0.0  0.575  8.297  67.0  2.4216   5.0  264.0   
411  0.03551  25.0   4.86   0.0  0.426  6.167  46.7  5.4007   4.0  281.0   
505  2.92400   0.0  19.58   0.0  0.605  6.101  93.0  2.2834   5.0  403.0   
450  0.05479  33.0   2.18   0.0  0.472  6.616  58.1  3.3700   7.0  222.0   
131  0.14476   0.0  10.01   0.0  0.547  5.731  65.2  2.7592   6.0  432.0   

     PTRATIO  
115     5.33  
334    14.64  
274     8.94  
231    17.19  
489    19.15  
..       ...  
461     7.44  
411     7.51  
505     9.81  
450     8.93  
131    13.61  

[404 rows x 11 columns]

In [19]:
y_train.size

404

In [20]:
X_train.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.425451   11.571782   10.961906    0.071782    0.550539    6.295547   
std      8.739111   23.234398    6.887719    0.258447    0.115294    0.695089   
min      0.009060    0.000000    0.460000    0.000000    0.385000    3.863000   
25%      0.080050    0.000000    5.130000    0.000000    0.448000    5.886500   
50%      0.243125    0.000000    8.560000    0.000000    0.524000    6.217500   
75%      2.844785   13.750000   18.100000    0.000000    0.624000    6.616500   
max     88.976200   95.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO  
count  404.000000  404.000000  404.000000  404.000000  404.000000  
mean    67.579208    3.876500    9.292079  405.126238   12.352327  
std     28.529384    2.095198    8.560040  166.393869    7.047701  
min      2.900000    1.129600    1.000000  188.000000    1.730000  
25%     42.275000    2.121425    4.000000  280.750000    6.710000  
50%     76.500000    3.375100    5.000000  330.000000   11.110000  
75%     93.650000    5.287300    8.000000  666.000000   16.530000  
max    100.000000   10.710300   24.000000  711.000000   34.770000

In [22]:
from sklearn.neural_network import MLPClassifier

In [23]:
clf = MLPClassifier(solver='sgd', alpha=1e-5, learning_rate_init = 0.01,
                    hidden_layer_sizes=(10, 10), random_state=1, max_iter = 500, verbose=True)

clf.fit(X_train, y_train)

Iteration 1, loss = 18.07747527
Iteration 2, loss = 5.35420644
Iteration 3, loss = 0.69317162
Iteration 4, loss = 0.60248498
Iteration 5, loss = 0.56445056
Iteration 6, loss = 0.57085118
Iteration 7, loss = 0.56230514
Iteration 8, loss = 0.56422906
Iteration 9, loss = 0.60500694
Iteration 10, loss = 0.61714954
Iteration 11, loss = 0.65079862
Iteration 12, loss = 0.56514729
Iteration 13, loss = 0.56703532
Iteration 14, loss = 0.56387732
Iteration 15, loss = 0.56377728
Iteration 16, loss = 0.56281084
Iteration 17, loss = 0.56666666
Iteration 18, loss = 0.56258533
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.


MLPClassifier(alpha=1e-05, hidden_layer_sizes=(10, 10), learning_rate_init=0.01,
              max_iter=500, random_state=1, solver='sgd', verbose=True)

In [26]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

threshold = 0.5

train_preds = (clf.predict_proba(X_train)[:,1] >= threshold).astype(int)
test_preds = (clf.predict_proba(X_test)[:,1] >= threshold).astype(int)

print(confusion_matrix(y_test, test_preds))
print(classification_report(y_test, test_preds))

[[ 0 20]
 [ 0 82]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        20
         1.0       0.80      1.00      0.89        82

    accuracy                           0.80       102
   macro avg       0.40      0.50      0.45       102
weighted avg       0.65      0.80      0.72       102



C:\Users\Sai Vikram Alladi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sai Vikram Alladi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sai Vikram Alladi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
